# Site settings
title: Xye Blog
SEOTitle: xyeee 博客 | Xye Blog
header-img: img/post-bg-desk.jpg
email: xxyeee@gmail.com
description: "Every failure is leading towards success."
keyword: "Xye, Xye Blog, 萧烨的博客, xyeee, ctf, iPhone"
url: "http://xyeee.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xyeee/xyeee.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "hacker"
sidebar-avatar: /img/blog_xyeee.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     zhang-yun-tao-98
github_username:    xyeee
facebook_username:  ye.xiao.90813
#jianshu_username:   e71990ada2fd
twitter_username:   xye_james
#instagram_username:   xye_james




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0f342b6897bd23c6b59b                            #生成的clientID
  clientSecret: 241b5a3537a46ea34ea6d9395a52d1db95ab8e87    #生成的clientSecret
  repo: xyeee.github.io    #仓库名称
  owner: xyeee    #github用户名
  admin: xyeee
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: efeb99909913982743ee94f966bea5c0

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto            # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "xyeee",
        href: "http://xxyee.cn"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
